### ISSUE TITLE
org.joyrest.collection.MultiMap

### ISSUE THREAD

**Issue by krasa** [petrbouda/joyrest#2]
co takhle tam dat guavu?
http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/Multimap.html

**Comment by petrbouda** [comment]
Guava je prilis nafoukla pro nase ucely, neni dobre vyzadovat od vyvojaru guavu, kdyz ji nebudou v projektu potrebovat.

**Comment by krasa** [comment]
staci nakopirovat nekolik class :)
